services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tutorme

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      MONGODB_URL: "mongodb://admin:password@mongo:27017/tutorme?authSource=admin"
      NODE_ENV: development
      JWT_SECRET: "your-jwt-secret-key-here"
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: ["node", "src/index.js"]

volumes:
  mongo_data:
